add new endpoint getCommonFilms
KurakinPavel/java-filmorate pull request #22
Opened 2024-04-03 00:44 UTC by OlerixXx

2024-04-04 17:27 UTC, AlbinaKuznetsova requested changes
Добавила комментарий по поводу запроса

2024-04-04 17:27 UTC, AlbinaKuznetsova commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                        commonPartOfQuery() + ") AS result INNER JOIN (" + commonIds + ") AS ids ON result.FILM_ID = ids.FILM_ID;", userId, friendId
Я думаю, объединение таблиц с помощью
INNER JOIN (" + commonIds + ") AS ids ON result.FILM_ID = ids.FILM_ID;
лучше заменить на 
WHERE FILM_ID IN (commonIds);
При этом commonIds оставить таким:
String commonIds = "SELECT l1.FILM_ID FROM LIKES l1 JOIN LIKES l2 ON l1.FILM_ID = l2.FILM_ID WHERE l1.USER_ID = ? AND l2.USER_ID = ?";

То есть, итоговый запрос будет:
SqlRowSet commonFilmsRows = jdbcTemplate.queryForRowSet(
                "SELECT RESULT.FILM_ID, RESULT.NAME, RESULT.DESCRIPTION, RESULT.RELEASE_DATE, RESULT.DURATION, RESULT.MPA_ID, RESULT.MPA, RESULT.GENRES_FOR_PARSING FROM (" +
                        commonPartOfQuery() + ") AS result WHERE FILM_ID IN (commonIds);", userId, friendId);

Чтобы не вытаскивать лишнюю таблицу для INNER JOIN

2024-04-04 23:01 UTC, OlerixXx commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                        commonPartOfQuery() + ") AS result INNER JOIN (" + commonIds + ") AS ids ON result.FILM_ID = ids.FILM_ID;", userId, friendId
Согласен. Оптимизировал SQL запросы. Результат ниже

2024-04-05 12:01 UTC, AlbinaKuznetsova approved these changes

2024-04-05 14:49 UTC, KurakinPavel reviewed
Конструкцию с IN (?, ?, ?, ...) необходимо заменить на конструкцию с PreparedStatement.

2024-04-05 14:49 UTC, KurakinPavel commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                        commonPartOfQuery() + ") AS RESULT WHERE RESULT.FILM_ID IN (" + commonIds + ");", userId, friendId
Конструкцию с IN (?, ?, ?, ...) необходимо заменить на конструкцию с PreparedStatement. Скрин ранее полученных замечаний ревьюера, и пример реализации из UserDbStorage прилагаются.
<img width="812" alt="про PreparedStatement" src="https://github.com/KurakinPavel/java-filmorate/assets/144927752/11086541-435d-4e26-82e2-e2c22189787e">
<img width="1131" alt="пример реализации" src="https://github.com/KurakinPavel/java-filmorate/assets/144927752/f3541a04-a036-4f41-aba1-5619e84a87e8">

2024-04-05 15:05 UTC, KurakinPavel approved these changes

2024-04-05 21:27 UTC, merged