ТЗ12: add-reviews
KurakinPavel/java-filmorate pull request #24
Opened 2024-04-03 15:23 UTC by KurakinPavel

2024-04-04 08:47 UTC, Siustoster requested changes
Оставил комменты под интересующими моментами

2024-04-04 08:47 UTC, Siustoster commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    private void validUserAndFilm(Review review) {
Контроллер не должен выполнять никакую логику, кроме передачи запросов в сервис. На мой взгляд, всю логику проверок и возврата ошибок лучше реализовать в сервисе

2024-04-04 08:47 UTC, Siustoster commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    private int validUserId(int userId) {
Для такой проверки достаточно аннотации @Positive в объявлении полей класса

2024-04-04 08:47 UTC, Siustoster commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    private int validFilmId(int filmId) {
Для такой проверки достаточно аннотации @Positive в объявлении полей класса

2024-04-04 08:47 UTC, Siustoster commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +public class ReviewService {
Вот примерно так должен выглядеть контроллер - без лишней логики) Лучше перенести логику обработки ошибок и проверки в сервис

2024-04-04 08:47 UTC, Siustoster commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +        return review;
При создании отзыва ты возвращаешь то, что прислали, а при апдейте возвращаешь то, что забираешь из бд после апдейта. На мой взгляд, лучше делать единообразно - забирать в обоих случаях данные, которые записались в бд.

2024-04-04 08:47 UTC, Siustoster commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +    private String commonPartOfQuery() {
А зачем метод? Чем не устраивает переменная\константа, если эта часть не должна меняться?

2024-04-04 08:47 UTC, Siustoster commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +    public Map<String, String> removeOpinionPositive(int reviewId, int userId) {
Мне кажется, или этот и следующий метод удаляют одно и то же? Если вызывать removeOpinionPositive, а пользователь оставил негативную оценку отзыву - удалится и негативная? На мой взгляд, надо проверять именно тип оценки отзыва, что б удалился нужного типа. Или сделать из этих двух методов один без проверки на то, какого типа оценка отзыва была удалена

2024-04-04 11:27 UTC, AlbinaKuznetsova commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +    private String commonPartOfQuery() {
В моей ветке в этот метод будет передаваться параметр, так что можно оставить)

2024-04-04 11:29 UTC, Siustoster commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +    private String commonPartOfQuery() {
Вопрос снят)

2024-04-04 12:29 UTC, AlbinaKuznetsova requested changes
Код еще не смотрела, у меня вопросы по хранению данных

2024-04-04 12:42 UTC, KurakinPavel commented on src/main/resources/schema.sql
> +        DIRECTION_ID INTEGER REFERENCES PUBLIC.DIRECTIONS(DIRECTION_ID) ON DELETE CASCADE,
Подумал, что кодами как-то правильнее. Условно, если добавляется ещё одно-два направление оценки (например, в сервисе "кинопоиск" есть положительные, отрицательные и нейтральные (серые) отзывы), или "отрицательное" нужно будет поменять на "нейтральное" - переделать схему хранения данных с кодами и отдельным справочником значений будет проще.

2024-04-04 12:53 UTC, KurakinPavel commented on src/main/resources/schema.sql
> +        GRADE_ID INTEGER REFERENCES PUBLIC.GRADES(GRADE_ID) ON DELETE CASCADE,
В "призовой", девятой "задаче со звёздочками", которую можно реализовать после сдачи основных восьми задач, предлагается заменить лайки (сейчас у меня это оценки 1 и -1) на оценки от 1 до 10 включительно, причём 1-5 - отрицательные, 6-10 - положительные. Такой рефакторинг проводить проще, когда шкала оценок, и признаки оценки вынесены в отдельную таблицу-справочник.

2024-04-04 14:37 UTC, KurakinPavel commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    private int validUserId(int userId) {
Я бы с удовольствием оставил бы только одну проверку аннотацией  "positive" (или "Min(1)") в поле класса, но это давало бы исключения только одного типа (MethodArgumentNotValidException - ошибка валидации), и код ответа был бы только 400 что не передай: null (фактически "0"), или "-1", как в некоторых тестах.
А у меня тесты требуют, чтобы возвращался код 500 (или 400) - когда в качестве id юзера или фильма передаётся null, и только 404 - когда на входе отрицательное значение. 
Соответственно, я вынужден раздельно возбуждать исключение при создании объекта, если передаётся null (в итоге возбуждается HttpMessageNotReadableException: JSON parse error, и код ответа 500, как и нужно), и если передаётся "-1" (возбуждается NoSuchElementException, и код ответа 404, как и нужно). Но из контроллера, конечно, перенёс в сервис.

2024-04-04 14:39 UTC, KurakinPavel commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    private void validUserAndFilm(Review review) {
Из контроллера проверка будет перенесена.

2024-04-04 14:39 UTC, KurakinPavel commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +public class ReviewService {
Да.

2024-04-04 14:40 UTC, KurakinPavel commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +        return review;
Будет исправлено.

2024-04-04 14:42 UTC, KurakinPavel commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +    public Map<String, String> removeOpinionPositive(int reviewId, int userId) {
Согласен.

2024-04-04 14:46 UTC, KurakinPavel commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    private int validFilmId(int filmId) {
Выше описал проблему, которая возникает из-за тестов.

2024-04-04 14:49 UTC, AlbinaKuznetsova commented on src/main/resources/schema.sql
> +        DIRECTION_ID INTEGER REFERENCES PUBLIC.DIRECTIONS(DIRECTION_ID) ON DELETE CASCADE,
Хорошо, согласна

2024-04-04 15:36 UTC, KurakinPavel commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +    public Map<String, String> removeOpinionPositive(int reviewId, int userId) {
Будет исправлено.

2024-04-05 12:40 UTC, AlbinaKuznetsova approved these changes

2024-04-05 12:48 UTC, merged