Add most populars
KurakinPavel/java-filmorate pull request #27
Opened 2024-04-05 15:04 UTC by AlbinaKuznetsova

Вывод самых популярных фильмов по жанру и годам

2024-04-05 15:30 UTC, KurakinPavel approved these changes
Всё хорошо.

2024-04-06 07:58 UTC, OlerixXx requested changes
В целом всё хорошо, добавил некоторые рекомендации

2024-04-06 07:58 UTC, OlerixXx commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private String commonPartOfQuery(boolean withGenre) {
Как по мне, изменение метода, лежащего в основе всех остальных методов - достаточно серьёзное мероприятие. Из за добавления параметра _boolean withGenre_ в метод _commonPartOfQuery()_ пришлось учитывать новый параметр почти во всех методах класса.


Я считаю, что тут можно использовать способ перегрузки метода:
```
private String commonPartOfQuery() {
    return commonPartOfQuery(false);
}
```

Тут мы задаём параметр по умолчанию в случае, если он не были передан в метод.
Таким образом мы избегаем конфликтных ситуаций при мёрже проекта с вашей веткой, а также не затрагиваем методы, написанные другими разработчиками.

2024-04-06 13:23 UTC, AlbinaKuznetsova commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private String commonPartOfQuery(boolean withGenre) {
Да, согласна, так будет лучше. Исправлю

2024-04-06 14:02 UTC, AlbinaKuznetsova commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private String commonPartOfQuery(boolean withGenre) {
Исправила

2024-04-06 14:12 UTC, OlerixXx approved these changes

2024-04-06 14:14 UTC, merged