new feature - getFilmRecommendations
KurakinPavel/java-filmorate pull request #29
Opened 2024-04-06 14:27 UTC by OlerixXx

2024-04-06 15:27 UTC, KurakinPavel approved these changes
Всё хорошо.

2024-04-06 18:55 UTC, AlbinaKuznetsova requested changes

2024-04-06 18:55 UTC, AlbinaKuznetsova commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public List<Film> getRecommendedFilms(Integer id) {
Мне кажется, что сейчас метод getRecommendedFilms предлагает пользователю все фильмы, у которых есть хотя бы один лайк (но которые не пролайкал сам пользователь). То есть, не ищутся максимальные пересечения по лайкам, как запрашивалось в ТЗ

2024-04-07 17:28 UTC, AlbinaKuznetsova commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public List<Film> getRecommendedFilms(Integer id) {
Обсудили с Павлом и решили, что такая реализация подходит, поэтому закрываю вопрос

2024-04-07 17:31 UTC, AlbinaKuznetsova approved these changes

2024-04-07 19:58 UTC, merged